### ISSUE TITLE
Expired certificate

### ISSUE THREAD

**Issue by tylerlaprade** [kalgynirae/lumeh.org#4]
<img width="1253" alt="image" src="https://github.com/kalgynirae/lumeh.org/assets/5475199/5425e376-9633-43d0-8bd9-4e09540fd144">
Seems like it happened at midnight last night, since I wasn't running into this while listening to music yesterday

**Comment by tylerlaprade** [comment]
This is also preventing Café Chan from playing music, but not the music page of lumeh.org
<img width="1692" alt="image" src="https://github.com/kalgynirae/lumeh.org/assets/5475199/56240bf2-170a-40bb-835c-3f519fbe2bb5">

**Comment by kalgynirae** [comment]
@tylerlaprade What browser were you using when this happened? I noticed some weirdness with Safari on my iPad (the cause of which I do not yet understand), but when I looked in other browsers it was fine and the certificate had correct dates.

**Comment by tylerlaprade** [comment]
Chrome on my MacBook. It occurred to me today that I may have still had cached certificates even though new ones were available if they happened to be renewing in a different timezone, but I haven't had a chance to test this yet (by clearing everything or using a different computer).

**Comment by tylerlaprade** [comment]
I just tested and everything works fine in Chrome on my personal MacBook. I have not re-tested my work MacBook (which is the one that experienced the issue), since I have not been working.

**Comment by tylerlaprade** [comment]
It works fine on my work computer as well, so I'll close this issue.
