### ISSUE TITLE
Music file cannot be found

### ISSUE THREAD

**Issue by tylerlaprade** [kalgynirae/lumeh.org#5]
<img width="382" alt="image" src="https://github.com/user-attachments/assets/c3ea04e9-a876-4f82-bab5-97634674cd6d">

P.S. Is it time for Christmas music?

**Comment by kalgynirae** [comment]
lol, I fixed this early afternoon yesterday without having seen your issue. You were just a bit too early!

Christmas music soon (maybe this weekend)
